spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: validate
  datasource:
    data: classpath:/data/h2/data.sql
    schema: classpath:/data/h2/schema.sql
    driver-class-name: org.h2.Driver

